#!/usr/bin/env tclsh
#
set script_dir [file dirname $argv0]
set HOME $env(HOME)
::tcl::tm::path add $HOME/lib/tcl8/site-tcl

package require jbr::msg
package require jbr::unix
package require jbr::with
package require jbr::dict
package require jbr::print
package require jbr::template
package require jbr::seconds

set env(WATER) .:4000
set env(MSGDEBUG) 1

msg_server WATER
msg_allow  WATER *
msg_publish WATER clk {} "clock seconds"

vwait forever
